language: de
# The language setting for the plugin. Ensure the corresponding language file exists in the messages folder; if not, create one.

disableEnd: true
# If set to true, players will be prevented from entering the End dimension.11

bypass:
  permission: antiend.bypass
  # Use 'antiend.*' to grant all related permissions.
  # The permission node required to bypass End entry restrictions.2

  allowBypass: false
  # If set to true, players with the specified permission or operator status can bypass the End entry restriction.

sendPreventMessage: true
# If enabled, the plugin will notify players when they are prevented from entering the End.

sendMessagesAsActionbar: true
# If enabled, messages from the plugin will be displayed as action bar messages instead of chat messages.

entryDisabledInWorlds:
  - world
  - world_nether
  # A list of worlds where entry into the End is restricted.
  # Players will be prevented from entering the End in these specified worlds.

disableJumpIntoPortal: true
# If set to true, players will be blocked from jumping into an End portal.
disableEnderEyeThrow: true
# If set to true, players will be unable to throw Ender Eyes.

sendCommandsOnPortalEnter:
  - "execute as %player% at @s run teleport @s ^ ^0.1 ^-2"
  # Moves the player back by 2 blocks and up by 0.1 blocks.
  # Only works if 'disableJumpIntoPortal' is true.
  # Define commands to be executed when a player enters an End portal.
  # You can use placeholders like %player% or %world%.

hologram:
  spaceBetweenEachLine: 0.2
  # The space between each line of text in the hologram.
  # Verwende "open", um das Ende den ganzen Tag offen zu halten.
  # Verwende "close", um das Ende den ganzen Tag geschlossen zu halten.
  # Gib eine Zeitspanne an (z. B. "8 - 10" oder "8am - 4pm"), damit das Ende nur in diesem Zeitraum offen ist.
  # Außerhalb dieser Zeiträume bleibt es geschlossen.
  schedule:
    enabled: false
    # If set to true, the End will only be accessible during the specified time.
    # If true and 'dynamicOpening.enabled' is also true, the dynamic opening will take precedence.
    monday: closed
    tuesday: 12 - 20
    wednesday: 15 - 16
    thursday: closed
    friday: open
    saturday: 8 - 12
    sunday: open

  dynamicOpening:
    enabled: false
    # If set to true, the End will open and close at specified intervals.
    # If true and 'schedule.enabled' is also true, the dynamic opening will take precedence.
    interval: 5  # Das Ende öffnet alle 5 Stunden.
    duration: 2  # Es bleibt für 2 Stunden geöffnet.
    # Nach dem Schließen bleibt es für (interval - duration) Stunden geschlossen.
    # Beispiel: Wenn interval=5 und duration=2, dann öffnet es alle 5 Stunden für 2 Stunden
    # und bleibt danach für 3 Stunden geschlossen, bevor der Zyklus wieder beginnt.